### ISSUE TITLE
Redundancy in timestamp function?

### ISSUE THREAD

**Issue by Hypercubed** [sethvincent/gameloop#1]
Maybe I am missing something but why is the `Game.prototype.timestamp` function checking for `global.performance` and `global.performance.now` if `global.performance.now`  is shimed?

**Comment by sethvincent** [comment]
Oh, you're right. That's definitely redundant. I'll happily merge a pull request if you want to send one, otherwise I'll refactor this sometime soon.

**Comment by Hypercubed** [comment]
I submitted a PR... however, I didn't test.  Please check.  You could also just call `global.performance.now` when needed instead of `timestamp`, but I didn't want to change your api.

... also, I'd like to borrow your shim for my engine, should I credit you?

**Comment by sethvincent** [comment]
This part of the code got factored out because of the added dependency `raf`, which I'd recommend using as a dependency in other modules.
