### ISSUE TITLE
Server context should use `setImmediate` and `process.nextTick(callback)`?

### ISSUE THREAD

**Issue by kevzettler** [sethvincent/gameloop#3]
Is there any value in using `setImmediate` or `process.nextTick` fallbacks for the server environment.

**Comment by sethvincent** [comment]
This part of the code got factored out because of the added dependency `raf`. But you're right, it may have been good to use something like [next-tick](http://npmjs.org/next-tick), which uses process.nextTick in node and other fallbacks for the browser.
